stages:
  - test
  - deploy

image: node:14.17.0-alpine

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

.default-cache: &default-cache
  before_script:
    - npm ci --cache .npm --prefer-offline

eslint:
  extends:
    - .default-cache
  stage: test
  script:
    - npm ci
    - npm run lint

prettier:
  extends:
    - .default-cache
  stage: test
  script:
    - npm ci
    - npm run check:format

deploy:
  image: ubuntu:latest
  stage: deploy
  script:
    - apt -qq update && apt upgrade -qqy openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - rsync -a --progress --human-readable --delete
      --exclude-from '.gitignore'
      --exclude .gitignore
      --exclude .git
      . deploy@130.193.43.58:~/realworld/
    - ssh deploy@130.193.43.58 "pushd ~/realworld && npm install && pm2 restart realworld && popd"
