name: Create review app

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    if: "!contains(github.event.pull_request.title, 'SKIP REVIEW')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: Adding known hosts
        run: ssh-keyscan -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts
      - name: Copy files to server
        run: |
            rsync -aqp --progress --human-readable --delete \
            --exclude-from '.gitignore' \
            --include-from .deploylist \
            --exclude public \
            --exclude ecosystem.config.js \
            . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/realworld/${{github.head_ref}}/
      - name: Restarting the app
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cp ~/realworld/ecosystem.config.js ~/realworld/${{github.head_ref}}/ && pushd ~/realworld/${{github.head_ref}} && sed -i 's/'DB_NAME': 'realworld'/'DB_NAME': '${{github.head_ref}}'/' ecosystem.config.js && chmod +x ./bin/create-db-copy && ./bin/create-db-copy ${{secrets.DB_PASSWORD}} ${{github.head_ref}} && npm install && pm2 restart ecosystem.config.js --name ${{github.head_ref}} --env production --update-env && popd"
      - name: Post review app URL
        if: success()
        uses: mshick/add-pr-comment@v1
        with:
          message: Created new review app at ${{ env.REVIEW_APP_URL }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          REVIEW_APP_URL: http://${{ github.head_ref }}.${{ secrets.APP_HOST }}/

  review:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - id: check-branch
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/git/ref/:ref
          owner: beCharlatan
          repo: react-redux-realworld-example-app
          ref: ${{github.head_ref}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        continue-on-error: true
      - if: steps.check-branch.output.status == 200
        name: Trigger frontend review app
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/publish-review-app.yml/dispatches
          owner: beCharlatan
          repo: react-redux-realworld-example-app
          ref: ${{github.head_ref}}
          inputs: |
            refName: ${{github.head_ref}}
            dst: ${{github.head_ref}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - if: steps.check-branch.output.status != 200
        name: Trigger frontend review app
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/publish-review-app.yml/dispatches
          owner: beCharlatan
          repo: react-redux-realworld-example-app
          ref: master
          inputs: |
            refName: "master"
            dst: ${{github.head_ref}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
