name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      - name: Copy files to the server
        run: |
          rsync -a --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --include-from .deploylist \
          --exclude public \
          . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/realworld/${{env.BRANCH}}/
      - name: Restart the application
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/realworld/${{env.BRANCH}} && npm install && cd ~/realworld && pm2 restart ecosystem.config.js"
