name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files to the server
        run: |
          rsync -a --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --include-from .deploylist \
          --exclude public \
          . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/realworld/$GITHUB_REF/
      - name: Restart the application
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pushd ~/realworld/$GITHUB_REF && npm install && popd && pm2 restart $GITHUB_REF"
