name: Reset database

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: Adding known hosts
        run: ssh-keyscan -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      - name: Resetting the database
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pushd ~/realworld/${{env.BRANCH}} && pm2 stop ecosystem.config.js && ./bin/create-db-copy ${{secrets.DB_PASSWORD}} ${{env.BRANCH}} && pm2 restart ecosystem.config.js --name ${{env.BRANCH}} --env production --update-env && popd"
